apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: cXVhcmt1cy10ZXN0LXVzZXI=
  mongo-password: cXVhcmt1cy10ZXN0LXVzZXItcGFzc3dvcmQ=
  mongo-database: cXVhcmt1c1Rlc3REQg==

