apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-backend-deployment
  labels:
    app: quarkus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-backend
  template:
    metadata:
      labels:
        app: quarkus-backend
    spec:
      containers:
        - name: quarkus-backend
          image: cbougos/quarkus-test-backend-native-scratch-upx
          ports:
            - containerPort: 8080
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-backend-service
spec:
  type: NodePort
  selector:
    app: quarkus-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
